// Ad Decisions Server
export const EMT_AD_DECISION_SERVER_URL = "https://d3hx2mfjmfgdc.cloudfront.net/v1/ads?duration=45";

export const EMT_AD_TRIGGERS = [
  "BREAK",
  "DISTRIBUTOR_ADVERTISEMENT",
  "DISTRIBUTOR_OVERLAY_PLACEMENT_OPPORTUNITY",
  "DISTRIBUTOR_PLACEMENT_OPPORTUNITY",
  "PROVIDER_ADVERTISEMENT",
  "PROVIDER_OVERLAY_PLACEMENT_OPPORTUNITY",
  "PROVIDER_PLACEMENT_OPPORTUNITY",
  "SPLICE_INSERT",
];
